version: "2.22.0"

services:
  db_auth:
    image: postgres
    container_name: db_auth
    ports:
      - "5432:5432"
    volumes:
      - "postgres:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_PASSWORD=root"
      - "POSTGRES_USER=root"
    restart: always
  app:
    build:
      context: .
    container_name: fast_api_app
    env_file:
      - .env
    ports:
      - "8001:8000"
    depends_on:
      - db_auth
volumes:
  postgres:

